language: python
dist: trusty
sudo: false
cache: pip
python: 3.6

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36

before_script:
  - pip install -U pip wheel tox
  - pip install -U pip wheel pylint

script:
  - pylint tuf
  - tox

after_success:
  - cd tests
  - coveralls
  - cd -

branches:
  only:
    - develop
    - pylint
